// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwa9uCbsYvo_OZIdcmNHnnbw8AVlynbbE',
    appId: '1:618151348931:web:c451f2c5cda94d82e8b076',
    messagingSenderId: '618151348931',
    projectId: 'cognitrack-dcede',
    authDomain: 'cognitrack-dcede.firebaseapp.com',
    storageBucket: 'cognitrack-dcede.firebasestorage.app',
    measurementId: 'G-G6EFWQJJE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwa9uCbsYvo_OZIdcmNHnnbw8AVlynbbE',
    appId: '1:618151348931:android:adb030d940ad438de8b076',
    messagingSenderId: '618151348931',
    projectId: 'cognitrack-dcede',
    storageBucket: 'cognitrack-dcede.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwa9uCbsYvo_OZIdcmNHnnbw8AVlynbbE',
    appId: '1:618151348931:ios:2d9ea09f7fd66928e8b076',
    messagingSenderId: '618151348931',
    projectId: 'cognitrack-dcede',
    storageBucket: 'cognitrack-dcede.firebasestorage.app',
    iosBundleId: 'com.cognitrack.cognitrack_mobile',
  );
}
